### ISSUE TITLE
Add a short adoc partial for each pipeline

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/configs#39]
- [ ] Add a short adoc partial for each pipeline
- [ ] Add new info stage to pipeline
    - [ ] In jarvis module as well
        - [ ] add adoc descriptions and copy into project
- [ ] print via cat in new info stage of pipeline
- [ ] Roll out to all repos
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/configs
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/website-masterblender-de
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-terraform
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/website-sommerfeld-io
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/dojo
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/jarvis
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/website-numero-uno-de
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-folderslint
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-adoc-antora
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-tf-graph-beautifier
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-jq
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/website-tafelboy-de
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/github-action-generate-readme
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-ftp-client
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/github-action-update-antora-yml
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/docker-image-git
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/github-action-generate-docs
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/monitoring
    - [ ] Adopt github.com/sebastian-sommerfeld-io/configs/issues/39 for https://github.com/sebastian-sommerfeld-io/trashbox
